import os
from sqlalchemy import create_engine, Column, String, Text, DateTime, JSON, inspect, text
from sqlalchemy.orm import declarative_base, sessionmaker
from datetime import datetime, timezone

DATA_DIR = os.environ.get("RETINA_DATA_DIR", "./data")
os.makedirs(DATA_DIR, exist_ok=True)

engine = create_engine(f"sqlite:///{os.path.join(DATA_DIR, 'retina.db')}")
SessionLocal = sessionmaker(bind=engine)
Base = declarative_base()


class Application(Base):
    __tablename__ = "applications"

    id = Column(String, primary_key=True)
    name = Column(String, nullable=False)
    connector_type = Column(String, nullable=False)
    credentials_encrypted = Column(Text, nullable=False)
    base_url = Column(String, nullable=True)
    last_sync = Column(DateTime, nullable=True)
    sync_schedule = Column(String, nullable=True)  # cron expression or preset like "daily", "weekly"
    sync_enabled = Column(String, default="false")  # "true" or "false"
    last_sync_status = Column(String, nullable=True)  # "success", "error: message"


class AccessSnapshot(Base):
    __tablename__ = "access_snapshots"

    id = Column(String, primary_key=True)
    application_id = Column(String, nullable=False, index=True)
    synced_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    users = Column(JSON, nullable=False)


class RetinaUser(Base):
    __tablename__ = "retina_users"

    id = Column(String, primary_key=True)
    email = Column(String, unique=True, nullable=False, index=True)
    name = Column(String, nullable=False)
    role = Column(String, default="reviewer")  # "admin" or "reviewer"
    is_active = Column(String, default="true")
    last_login = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class ReviewItem(Base):
    __tablename__ = "review_items"

    id = Column(String, primary_key=True)
    application_id = Column(String, nullable=False, index=True)
    application_name = Column(String, nullable=False)
    snapshot_id = Column(String, nullable=False)
    user_email = Column(String, nullable=False, index=True)
    user_name = Column(String, nullable=True)
    status = Column(String, default="pending")  # "pending", "approved", "flagged", "resolved"
    notes = Column(Text, nullable=True)
    reviewed_by = Column(String, nullable=True)
    reviewed_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    # NULL = ad-hoc item (unchanged legacy behavior). Set when generated by a review cycle.
    cycle_id = Column(String, nullable=True, index=True)
    product_id = Column(String, nullable=True, index=True)
    assigned_reviewer_email = Column(String, nullable=True, index=True)  # comma-joined if a product has multiple reviewers


class AuditLog(Base):
    __tablename__ = "audit_log"

    id = Column(String, primary_key=True)
    action = Column(String, nullable=False)  # "flag", "approve", "resolve", "cycle_generated", "reminder_sent", "escalation_sent"
    actor_email = Column(String, nullable=False)
    target_email = Column(String, nullable=True)
    application_name = Column(String, nullable=True)
    details = Column(Text, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    cycle_id = Column(String, nullable=True, index=True)


class Product(Base):
    """A business-level grouping of one or more Applications, for scoping a review cycle."""
    __tablename__ = "products"

    id = Column(String, primary_key=True)
    name = Column(String, nullable=False, unique=True)
    description = Column(Text, nullable=True)
    slack_webhook_url_encrypted = Column(Text, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class ProductScope(Base):
    """One Application's membership in a Product, with an optional sub-resource filter
    evaluated against each user's synced JSON fields (e.g. field='roles', match='contains',
    value='payments-team')."""
    __tablename__ = "product_scopes"

    id = Column(String, primary_key=True)
    product_id = Column(String, nullable=False, index=True)
    application_id = Column(String, nullable=False, index=True)
    filter_field = Column(String, nullable=True)
    filter_match = Column(String, nullable=True)  # "equals" or "contains"
    filter_value = Column(String, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class ProductReviewer(Base):
    __tablename__ = "product_reviewers"

    id = Column(String, primary_key=True)
    product_id = Column(String, nullable=False, index=True)
    reviewer_email = Column(String, nullable=False, index=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class ReviewCycle(Base):
    """A time-boxed review campaign, e.g. 'Q3 2026 SOC 2 Review'."""
    __tablename__ = "review_cycles"

    id = Column(String, primary_key=True)
    name = Column(String, nullable=False)
    status = Column(String, default="active")  # "active" or "closed"
    due_date = Column(DateTime, nullable=False)
    scope_all_applications = Column(String, default="false")  # "true" or "false"
    generation_status = Column(String, default="pending")  # "pending", "generating", "done", "error"
    generation_summary = Column(Text, nullable=True)  # JSON-encoded warnings/counts from the last generation run
    created_by = Column(String, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    closed_at = Column(DateTime, nullable=True)


class CycleScope(Base):
    """Which Products are in-scope for a cycle (unused if scope_all_applications is true)."""
    __tablename__ = "cycle_scopes"

    id = Column(String, primary_key=True)
    cycle_id = Column(String, nullable=False, index=True)
    product_id = Column(String, nullable=False, index=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class SentReminder(Base):
    """Dedup record so the periodic reminder job doesn't re-notify for the same threshold."""
    __tablename__ = "sent_reminders"

    id = Column(String, primary_key=True)
    cycle_id = Column(String, nullable=False, index=True)
    product_id = Column(String, nullable=False, index=True)
    threshold = Column(String, nullable=False)  # "7d", "3d", "1d", or "overdue_2026-07-15"
    sent_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


def _ensure_columns():
    """Add columns introduced after initial release to an existing SQLite file.
    Base.metadata.create_all() only creates missing tables, it never alters
    existing ones, so pre-existing installs need this to pick up new columns."""
    inspector = inspect(engine)
    existing_tables = set(inspector.get_table_names())

    additions = {
        "review_items": [
            ("cycle_id", "VARCHAR"),
            ("product_id", "VARCHAR"),
            ("assigned_reviewer_email", "VARCHAR"),
        ],
        "audit_log": [
            ("cycle_id", "VARCHAR"),
        ],
    }

    with engine.begin() as conn:
        for table, columns in additions.items():
            if table not in existing_tables:
                continue
            existing_cols = {c["name"] for c in inspector.get_columns(table)}
            for name, sql_type in columns:
                if name not in existing_cols:
                    conn.execute(text(f"ALTER TABLE {table} ADD COLUMN {name} {sql_type}"))


def init_db():
    _ensure_columns()
    Base.metadata.create_all(engine)


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
